### ISSUE TITLE
 "publicPath": "http://www.baidu.com.com“

### ISSUE THREAD

**Issue by amandaXCY** [typedoc2md/typedoc-plugin-markdown#621] opened 2024-05-21 10:01 UTC
### What package is the bug related to?

typedoc-plugin-markdown

### Describe the issue

config里配置了 "publicPath": "http://www.baidu.com.com/a/b“
生成出来：
[StorageManager](http:/www.baidu.com.com/a/b/*) 

### TypeDoc configuration

{
    // Comments are supported, like tsconfig.json
    "entryPoints": ["./src/index.tsx"],
    "out": "docs",
    "compilerOptions": {
        "strictNullChecks": false,
    },
    "entryFileName": "../README.md",
    "exclude":["./node_modules/**/*.ts"],
    "groupOrder": [ "Classes","Namespaces", "Functions","*"],
    "excludeGroups": false,
    "mergeReadme":"none",

    "categorizeByGroup": true,
    "membersWithOwnFile": ["Enum", "Variable", "Function", "Class","TypeAlias","Interface"],
    "plugin": ["typedoc-plugin-markdown","typedoc-plugin-remark","typedoc-plugin-missing-exports","typedoc-plugin-rename-defaults","typedoc-gitlab-wiki-theme"],
    "entryModule": "none",
    "publicPath": "http://baidu.com/a/b",
    "outputFileStrategy":"members",
    "flattenOutputFiles": false,
    "expandParameters": false,
    "expandObjects": false,
    "parametersFormat": "table",
    "enumMembersFormat": "table",
    "propertiesFormat": "table",
    "indexFormat": "table",
    "typeDeclarationFormat": "table",
    "hidePageHeader": true,
    "textContentMappings": {
        "header.title": "{projectName} {version}",
        "header.docs": "Docs",
        "breadcrumbs.home": "{projectName} {version}",
        "footer.text": "",
        "title.indexPage": "{projectName} {version}",
        "title.modulePage": "{name}",
        "title.memberPage": "{kind}: {name}",
        "label.apiIndex": "API Index",
        "label.defaultValue": "默认值",
        "label.description": "描述",
        "label.extendedBy": "Extended by",
        "label.extends": "Extends",
        "label.flags": "Flags",
        "label.globals": "全局",
        "label.implements": "Implements",
        "label.implementationOf": "Implementation of",
        "label.inheritedFrom": "Inherited from",
        "label.index": "Index",
        "label.indexable": "Indexable",
        "label.indexSignature": "Index signature",
        "label.member": "Member",
        "label.modifier": "Modifier",
        "label.name": "Name",
        "label.overrides": "Overrides",
        "label.packages": "Packages",
        "label.reExports": "Re-exports",
        "label.renamesAndReExports": "Renames and re-exports",
        "label.returns": "Returns",
        "label.source": "来源",
        "label.type": "类型",
        "label.typeDeclaration": "Type declaration",
        "label.value": "Value",
        "kind.accessor.singular": "Accessor",
        "kind.accessor.plural": "Accessors",
        "kind.class.singular": "Class",
        "kind.class.plural": "Classes",
        "kind.constructor.singular": "Constructor",
        "kind.constructor.plural": "Constructors",
        "kind.enum.singular": "Enumeration",
        "kind.enum.plural": "Enumerations",
        "kind.enumMember.singular": "Enumeration Member",
        "kind.enumMember.plural": "Enumeration Members",
        "kind.event.singular": "Event",
        "kind.event.plural": "Events",
        "kind.function.singular": "Function",
        "kind.function.plural": "Functions",
        "kind.interface.singular": "Interface",
        "kind.interface.plural": "Interfaces",
        "kind.method.singular": "Method",
        "kind.method.plural": "Methods",
        "kind.module.singular": "Module",
        "kind.module.plural": "Modules",
        "kind.namespace.singular": "Namespace",
        "kind.namespace.plural": "Namespaces",
        "kind.variable.singular": "Variable",
        "kind.variable.plural": "Variables",
        "kind.parameter.singular": "参数",
        "kind.parameter.plural": "参数",
        "kind.property.singular": "Property",
        "kind.property.plural": "Properties",
        "kind.reference.singular": "Reference",
        "kind.reference.plural": "References",
        "kind.typeAlias.singular": "Type alias",
        "kind.typeAlias.plural": "Type Aliases",
        "kind.typeParameter.singular": "Type parameter",
        "kind.typeParameter.plural": "Type parameters",
      }
}

**Comment by tgreyuk** [comment] 2024-05-21 12:36
Hi. Thanks for raising the issue. 

Could you be a bit more specific please on what the problem is as I can't replicate any issue?

In your initial config you have written :

```
"publicPath": "http://www.baidu.com.com/a/b"
```

**Comment by tgreyuk** [comment] 2024-05-23 07:42
I cannot view the image and i am still not sure what the issue is. Sorry :(

**Comment by tgreyuk** [comment] 2024-06-22 10:58
Closing as not sure what the issue is. Please feel free to re-open.

**Closed by tgreyuk** 2024-06-22 10:58 UTC
Labels: bug
