### ISSUE TITLE
[typedoc-plugin-markdown] How to change title format

### ISSUE THREAD

**Issue by Dr-Electron** [typedoc2md/typedoc-plugin-markdown#450] opened 2023-07-19 22:04 UTC
Hi, 
Currently we are using your project to create markdown files which we import in Docusaurus. But the title of the the pages is always `Type: TypeName`. For example: `Class: SomeClass`. In Docusaurus that creates the following sidebar structure:

```
Classes/
├── Class: SomeClass
└── Class: AnotherClass
```

Would be nice if the title could be customised to only have `SomeClass` as title.

I'm not sure if any other plugin like the frontmatter one could help here 🤔

**Comment by NicolasThierion** [comment] 2023-07-28 15:49
I also wish there was an option to override the Handlebars helpers. At the moment, here is my hacky workaround: 


```ts
    // override helper to exclude ReflectionKind from sidebar
    Handlebars.registerHelper(
      'reflectionTitle',
      function (shouldEscape = true) {
        const title = [''];
        title.push(
          shouldEscape ? escapeChars(this.model.name) : this.model.name,
        );
        if (this.model.typeParameters) {
          const typeParameters = this.model.typeParameters
            .map((typeParameter) => typeParameter.name)
            .join(', ');
          title.push(`<${typeParameters}${shouldEscape ? '\\>' : '>'}`);
        }
        return title.join('');
      },
    );
    const _registerHelper = Handlebars.registerHelper;
    Handlebars.registerHelper = function (...args): void {
      if (args[0] === 'reflectionTitle') {
        return;
      }

      return _registerHelper.apply(Handlebars, args);
    };

    function escapeChars(str) {
      return str
        .replace(/>/g, '\\>')
        .replace(/_/g, '\\_')
        .replace(/`/g, '\\`')
        .replace(/\|/g, '\\|');
    }
    ```

**Comment by Dr-Electron** [comment] 2024-03-01 14:13
@tgreyuk cool just tried out `next` and it works like intended. 

But I had to remove the `--theme markdown` option for it to work.
And the docs went from looking like this:
<img width="950" alt="Bildschirmfoto 2024-03-01 um 15 12 36" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/61637085/f7b489f0-5b57-4df2-968d-622bb288658f">

To this:
<img width="939" alt="Bildschirmfoto 2024-03-01 um 15 12 58" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/61637085/45395b8c-f60e-4a5f-984f-86fe90dbe03b">

Why is there a slash after `Promise` now? And also if I would like to keep the table format, would that be possible?

**Comment by tgreyuk** [comment] 2024-03-01 17:08
Hi @Dr-Electron,

> Why is there a slash after Promise now?

There shouldn't be. Is this output from Docusaurus?

> And also if I would like to keep the table format, would that be possible?

This can be achieved with `--parametersFormat table`. There is actually a bunch of new options https://www.typedoc-plugin-markdown.org/options .

**Comment by Dr-Electron** [comment] 2024-03-01 21:19
> There shouldn't be. Is this output from Docusaurus?

We import it in docusaurus but it is not generated by the docusaurus plugin. (We pull the reference docs from outside of docusaurus).
Should I create another issue for that problem?

> > And also if I would like to keep the table format, would that be possible?
> 
> This can be achieved with `--parametersFormat table`. There is actually a bunch of new options https://www.typedoc-plugin-markdown.org/options .


Lovely ❤️ . Really nice changes you made in the next version ❤️

**Comment by tgreyuk** [comment] 2024-03-02 17:40
> We import it in docusaurus but it is not generated by the docusaurus plugin. (We pull the reference docs from outside of docusaurus).

Ok, I assume you are using Docusaurus 2?. The issue is that the output is now MDX but Docusaurus is not MDX compatible (this is handled by the Docusaurus plugin). This looks to be the same issue as raised here https://github.com/tgreyuk/typedoc-plugin-markdown/issues/564 .  I think the best thing here is to offer an opt-out of MDX.

**Comment by tgreyuk** [comment] 2024-03-02 19:31
@Dr-Electron in the mean time i've had another idea. You can use the docusaurus-plugin without executing `build` or `start` with an exposed cli command `generate-typedoc`. So you could install docusaurus-plugin-typedoc@next and then run `docusaurus generate-typedoc` rather than `typedoc`. This should fix/remove the escaped angle brackets.

**Comment by Dr-Electron** [comment] 2024-03-04 14:24
> @Dr-Electron in the mean time i've had another idea. You can use the docusaurus-plugin without executing `build` or `start` with an exposed cli command `generate-typedoc`. So you could install docusaurus-plugin-typedoc@next and then run `docusaurus generate-typedoc` rather than `typedoc`. This should fix/remove the escaped angle brackets.

The problem with this is, that I need to install docusaurus in that repo too. Only to generate the docs, which are then uploaded and used by the main docusaurus project 😅

**Comment by tgreyuk** [comment] 2024-05-04 21:31
Closing this as original issue fixed. 

The mdx issues should be fixed by adding the following to `docusuaurus.config`:

```
  markdown: {
    format: 'detect'
  },
```

**Closed by tgreyuk** 2024-05-04 21:31 UTC
Labels: next
